MarkomApp/Controllers/m_EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MA_DataModel;
using MA_ViewModel;
using MA_Repository;

namespace MarkomApp.Controllers
{
    public class m_EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            ViewBag.CompanyName = new SelectList(m_CompanyRepo.All(), "id", "name");
            return View();
        }
 
        public ActionResult List(int page, string searchID, string searchName, string createBy, int perPage)
        {
            Pagination pg = m_EmployeeRepo.Paging(page, searchID, searchName, createBy, perPage);
            ViewBag.currPage = page;
            ViewBag.PageCount = pg.Pages;
            return PartialView("_List", pg.ListOf);
        }

        public ActionResult SearchDate(DateTime createDate)
        {
            return PartialView("_List", m_EmployeeRepo.SearchDate(createDate));
        }

        //Get
        public ActionResult Create()
        {
            ViewBag.CompanyList = new SelectList(m_CompanyRepo.All(), "id", "name");
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(m_EmployeeView model)
        {
            ResponseResult result = m_EmployeeRepo.Create(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    entity = result.Entity
                },
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult Detail(long id)
        {
            return PartialView("_Detail", m_EmployeeRepo.ById(id));
        }

        //Get
        public ActionResult Edit(long id)
        {
            ViewBag.CompanyList = new SelectList(m_CompanyRepo.All(), "id", "name");
            return PartialView("_Edit", m_EmployeeRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Edit(m_EmployeeView model)
        {
            ResponseResult result = m_EmployeeRepo.Edit(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);
        }

        //Get
        public ActionResult Delete(long id)
        {
            return PartialView("_Delete", m_EmployeeRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Delete(m_employee model)
        {
            ResponseResult result = m_EmployeeRepo.Delete(model.id);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);

        }

    }
}

MarkomApp/Views/m_Employee/Index.cshtml
<br />
<div class="panel panel-primary">
    <div class="panel-heading">
        <p style="font-size:15px">List Employee</p>
    </div>
    <div class="panel-body">
        <span class="label label-default" style="background-color: #EFEDED; font-size: 14px; color: grey"> @Html.ActionLink("Home", "Index", "Home") / @Html.ActionLink("List Employee", "Index", "m_Employee")</span>
        <br />
        <div class="row">
            <div id="alertbox">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 text-right">
                <button type="button" class="btn btn-md btn-primary" onclick="AddEmployee()">
                    Add
                </button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <input type="search" id="searchID" class="form-control" style="width:185px" placeholder="Employee ID Number" />
            </div>
            <div class="col-md-2">
                <input type="search" id="searchName" class="form-control" style="width:185px" placeholder="Employee Name" />
            </div>
            <div class="col-md-3">
                @Html.DropDownList("searchComp", (SelectList)ViewBag.CompanyName, "- Select Company Name -", new { @class = "form-control", id = "searchComp", style = "max-width: 210px" })
            </div>
            <div class="col-md-2">
                <div class="input-group date">
                    <input type="text" id="createdate" class="form-control" style="width:150px; border-right: none" placeholder="Created" onfocus="(this.type='date')" onblur="(this.type='text')">
                    <span class="input-group-addon btn" style="border-left:none; background: white">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                <input type="search" id="createby" class="form-control" style="width:185px" placeholder="Created By" />
            </div>
            <div class="col-md-1">
                <button type="button" id="btn-search" class="btn btn-md btn-warning">
                    Search
                </button>
            </div>
        </div>
        <div id="list-body">
            Loading...
        </div>
    </div>
</div>

<div id="modal1" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document" style="width: 750px">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <button type="button" style="color: white" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" style="color: white; font-size: 18px">Employee</h3>
            </div>
            <div class="modal-body">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="modal-delete" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document" style="width: 230px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close btn-danger" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body" id="body-delete">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts{
    <script type="text/javascript">
        var currPage = 1;
        var maxPage = 1;
        var perPage = 10;
        var searchID = "";
        var searchName = "";
        var searchComp = 4;
        var createDate;
        var createBy = "";

        $(document).ready(function () {
            GetList()
        })

        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "m_Employee")',
                type: 'get',
                data: { page: currPage, searchID: searchID, searchName: searchName, perPage: perPage, createBy: createBy },
                success: function (result) {
                    $("#list-body").html(result);
                    if (result = null) {
                        $("#list-body").html("Hasil tidak ditemukan");
                    }
                    if (currPage == 1) {
                        $('#btn-prev').addClass('disabled');
                    };
                }
            });
        }

        $("#btn-search").click(function () {
            searchID = $("#searchID").val();
            searchName = $("#searchName").val();
            searchComp = $("#searchComp").val();
            createDate = $("#createdate").val();
            createBy = $("#createby").val();
            if (createDate == "") {
                GetList();
            } else {
                $.ajax({
                    url: '@Url.Action("SearchDate","m_Employee")',
                    type: 'get',
                    data: { createDate: createDate },
                    success: function (result) {
                        $("#list-body").html(result);
                    }
                });
            }
        })

        function AddEmployee() {
            $.ajax({
                url: '@Url.Action("Create", "m_Employee")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal1").modal("show");
                    $(".modal-title").html("Add Employee");
                }
            });
        }

        function DetailById(id) {
            $.ajax({
                url: '@Url.Action("Detail", "m_Employee")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("View Employee");
                    $("#modal1").modal("show");
                }
            });
        }

        function GetById(id) {
            $.ajax({
                url: '@Url.Action("Edit", "m_Employee")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Edit Employee");
                    $("#modal1").modal("show");
                }
            });
        }

        function DeleteById(id) {
            $.ajax({
                url: '@Url.Action("Delete", "m_Employee")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $("#body-delete").html(result);
                    $("#modal-delete").modal("show");
                }
            });
        }

        function rowPage(obj) {
            perPage = $(obj).attr('data-row');
            currPage = 1;
            GetList();
        }

        $("#btn-prev").click(function () {
            if (currPage > 1) {
                currPage--;
                $('#btn-next').removeClass('disabled');
            }
            GetList(currPage, perPage);
        });

        $("#btn-next").click(function () {
            if (currPage < maxPage) {
                currPage++;
                $('#btn-prev').removeClass('disabled');
            }
            GetList(currPage, perPage);
        });

        function DataSaved() {
        var saved = '<div class="alert alert-info alert-dismissible" role="alert"> <strong>Data Saved!</strong> New employee has been add <strong>!</strong> </div>';
        $("#alertbox").html(saved);
        $("#alertbox").slideUp(5000, function () {
            GetList();
        });
    }

    function DataUpdated() {
        var updated = '<div class="alert alert-info alert-dismissible" role="alert"> <strong>Data Updated!</strong> Data employee has been updated <strong>!</strong> </div>';
        $("#alertbox").html(updated);
        $("#alertbox").slideUp(5000, function () {
            GetList();
        });
    }

    function DataDeleted() {
        var deleted = '<div class="alert alert-info alert-dismissible" role="alert"> <strong>Data Deleted!</strong> Data employee has been deleted <strong>!</strong> </div>';
        $("#alertbox").html(deleted);
        $("#alertbox").slideUp(5000, function () {
            GetList();
        });
    }
    </script>
}

MarkomApp/Views/m_Employee/_Create.cshtml
@model MA_ViewModel.m_EmployeeView

@using (Html.BeginForm("Create", "m_Employee", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <p class="col-md-5 text-right">* Emp ID Number</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.employee_number, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Emp ID Number" } })
                        @Html.ValidationMessageFor(model => model.employee_number, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* First Name</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type First Name" } })
                        @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">Last Name</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Last Name" } })
                        @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <p class="col-md-5 text-right">* Company Name</p>
                    <div class="col-md-7">
                        @Html.DropDownListFor(model => model.m_company_id, (IEnumerable<SelectListItem>)ViewBag.CompanyList, "- Select Company Name -", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.m_company_id, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">Email</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Email" } })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12 text-right">
                <div class="form-actions">
                    <input type="submit" value="Save" class="btn btn-primary" style="width: 80px" />
                    <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-warning" style="width: 80px" />
                </div>
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    var ent = result.entity;
                    $("#modal1").modal("hide");                    
                    DataSaved();
                }
            }
        })
        return false;
    })
</script>

MarkomApp/Views/m_Employee/_Delete.cshtml
@model MA_ViewModel.m_EmployeeView

<div>
    <div class="form-horizontal">
        <div class="row">
            <div class="col-md-12 text-center" style="font-size: 15px">
                Delete Data ? <br /> <br />
            </div>
        </div>
    </div>

    @using (Html.BeginForm("Delete", "m_Employee", FormMethod.Post, new { id = "form-delete", name = "form-delete" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id)
        <div class="col-md-offset-1">
            <div class="form-actions">
                <input type="submit" value="Delete" class="btn btn-primary" style="width: 80px" />
                <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-warning" style="width: 80px" />
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $("#form-delete").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#modal-delete").modal("hide");
                    DataDeleted()
                } else {
                    alert('Error: ' + result.message);
                }
            }
        })
        return false;
    })
</script>

MarkomApp/Views/m_Employee/_Detail.cshtml
@model MA_ViewModel.m_EmployeeView
@Html.AntiForgeryToken()

@Html.HiddenFor(model => model.id)

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <p class="col-md-5 text-right">* Emp ID Number</p>
                <div class="col-md-7">
                    @Html.EditorFor(model => model.employee_number, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.employee_number, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <p class="col-md-5 text-right">* First Name</p>
                <div class="col-md-7">
                    @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <p class="col-md-5 text-right">Last Name</p>
                <div class="col-md-7">
                    @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <p class="col-md-5 text-right">* Company Name</p>
                <div class="col-md-7">
                    @Html.EditorFor(model => model.company_name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.m_company_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <p class="col-md-5 text-right">Email</p>
                <div class="col-md-7">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-12 text-right">
            <input type="button" value="Close" data-dismiss="modal" class="btn btn-warning" style="width: 80px" />
        </div>
    </div>
</div>

MarkomApp/Views/m_Employee/_Edit.cshtml
@model MA_ViewModel.m_EmployeeView

@using (Html.BeginForm("Edit", "m_Employee", FormMethod.Post, new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <p class="col-md-5 text-right">* Emp ID Number</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.employee_number, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Emp ID Number" } })
                        @Html.ValidationMessageFor(model => model.employee_number, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* First Name</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type First Name" } })
                        @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">Last Name</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Last Name" } })
                        @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <p class="col-md-5 text-right">* Company Name</p>
                    <div class="col-md-7">
                        @Html.DropDownListFor(model => model.m_company_id, (IEnumerable<SelectListItem>)ViewBag.CompanyList, "- Select Company Name -", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.m_company_id, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">Email</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Email" } })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12 text-right">
                <div class="form-actions">
                    <input type="submit" value="Update" class="btn btn-primary" id="update" style="width: 80px" />
                    <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-warning" style="width: 80px" />
                </div>
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#form-edit").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    var ent = result.entity;
                    $("#modal1").modal("hide");                       
                    DataUpdated();
                }
            }
        })
        return false;
    })
</script>

MarkomApp/Views/m_Employee/_List.cshtml
@model IEnumerable<MA_ViewModel.m_EmployeeView>

<style>
    .table {
        counter-reset: serial-number;
    }

        .table td:first-child:before {
            counter-increment: serial-number;
            content: counter(serial-number);
        }
</style>

<table class="table">
    <tr>
        <th>No</th>
        <th>Employee ID Number</th>
        <th>Employee Name</th>
        <th>Company Name</th>
        <th>Created Date</th>
        <th>Created By</th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.employee_number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.first_name) @Html.DisplayFor(modelItem => item.last_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.company_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.createdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.created_by)
            </td>
            <td>
                <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-default btn-detail" style="border:none" data-id="@item.id" title="View" onclick="DetailById(@item.id)">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                    <button type="button" class="btn btn-default btn-edit" style="border:none" data-id="@item.id" title="Edit" onclick="GetById(@item.id)">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </button>
                    <button type="button" class="btn btn-default btn-delete" style="border:none" data-id="@item.id" onclick="DeleteById(@item.id)" title="Delete">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </div>
            </td>
        </tr>
    }

</table>

<div class="col-md-offset-5 text-right">
    <button type="button" class="btn btn-primary" id="btn-prev">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
    </button>
    <span class="btn" style="border-color: grey; background: none; color: steelblue">@ViewBag.currPage</span>

    <button type="button" class="btn btn-primary" id="btn-next">
        <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
    </button>
</div>