MarkomApp/Controllers/m_RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MA_DataModel;
using MA_ViewModel;
using MA_Repository;

namespace MarkomApp.Controllers
{
    public class m_RoleController : Controller
    {
        // GET: Role
        public ActionResult Index()
        {
            ViewBag.RoleCode = new SelectList(m_RoleRepo.All(), "code", "code");
            ViewBag.RoleName = new SelectList(m_RoleRepo.All(), "name", "name");
            ViewBag.Code = m_RoleRepo.GetNewCode();
            return View();
        }

        public ActionResult List(int page, string searchCode, string searchName, int perPage, string createBy)
        {
            Pagination pg = m_RoleRepo.Paging(page, searchCode, searchName, perPage, createBy);
            ViewBag.currPage = page;
            ViewBag.PageCount = pg.Pages;
            return PartialView("_List", pg.ListOf);
        }

        public ActionResult SearchDate(DateTime createDate)
        {
            return PartialView("_List", m_RoleRepo.SearchDate(createDate));
        }

        //Get
        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(m_RoleView model)
        {
            ResponseResult result = m_RoleRepo.Create(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    entity = result.Entity
                },
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult Detail(long id)
        {
            return PartialView("_Detail", m_RoleRepo.ById(id));
        }

        //Get
        public ActionResult Edit(long id)
        {
            return PartialView("_Edit", m_RoleRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Edit(m_RoleView model)
        {
            ResponseResult result = m_RoleRepo.Edit(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);
        }

        //Get
        public ActionResult Delete(long id)
        {
            return PartialView("_Delete", m_RoleRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Delete(m_role model)
        {
            ResponseResult result = m_RoleRepo.Delete(model.id);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);

        }

    }
}

MarkomApp/Views/m_Role/Index.cshtml
<br />
<div class="panel panel-primary">
    <div class="panel-heading">
        <p style="font-size:15px">List Role</p>
    </div>
    <div class="panel-body">
        <span class="label label-default" style="background-color: #EFEDED; font-size: 14px; color: grey"> @Html.ActionLink("Home", "Index", "Home") / @Html.ActionLink("List Role", "Index", "m_Role")</span>
        <br />
        <div class="row">
            <div id="alertbox">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 text-right">
                <button type="button" class="btn btn-md btn-primary" onclick="AddRole()">
                    Add
                </button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                @Html.DropDownList("searchCode", (SelectList)ViewBag.RoleCode, "- Select Role Code -", new { @class = "form-control", id = "searchCode", style = "max-width: 210px" })
            </div>
            <div class="col-md-3">
                @Html.DropDownList("searchName", (SelectList)ViewBag.RoleName, "- Select Role Name -", new { @class = "form-control", id = "searchName", style = "max-width: 210px" })
            </div>
            <div class="col-md-3">
                <div class="input-group date">
                    <input type="text" id="createdate" class="form-control" style="width:210px; border-right: none" placeholder="Created" onfocus="(this.type='date')" onblur="(this.type='text')">
                    <span class="input-group-addon btn" style="border-left:none; background: white">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                <input type="search" id="createby" class="form-control" style="width:140px" placeholder="Created By" />
            </div>
            <div class="col-md-1">
                <button type="button" id="btn-search" class="btn btn-md btn-warning">
                    Search
                </button>
            </div>
        </div>
        <div id="list-body">
            Loading...
        </div>
    </div>
</div>

<div id="modal1" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document" style="width: 400px">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <button type="button" style="color: white" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" id="pop-title" style="color: white; font-size: 18px">Role</h3>
            </div>
            <div class="modal-body">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="modal-delete" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document" style="width: 230px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close btn-danger" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body" id="body-delete">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts{
    <script type="text/javascript">
        var currPage = 1;
        var maxPage = 1;
        var searchCode = "";
        var searchName = "";
        var perPage = 10;
        var createDate;
        var createBy = "";

        $(document).ready(function () {
            GetList()
        })

        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "m_Role")',
                type: 'get',
                data: { page: currPage, searchCode: searchCode, searchName: searchName, perPage: perPage, createBy: createBy },
                success: function (result) {
                    $("#list-body").html(result);
                    if (result = null) {
                        $("#list-body").html("Hasil tidak ditemukan");
                    }
                    if (currPage == 1) {
                        $('#btn-prev').addClass('disabled');
                    };
                }
            });
        }

        $("#btn-search").click(function () {
            searchCode = $("#searchCode").val();
            searchName = $("#searchName").val();
            createDate = $("#createdate").val();
            createBy = $("#createby").val();
            if (createDate == "") {
                GetList();
            } else {
                $.ajax({
                    url: '@Url.Action("SearchDate","m_Role")',
                    type: 'get',
                    data: { createDate: createDate },
                    success: function (result) {
                        $("#list-body").html(result);
                    }
                });
            }

        })

        function AddRole() {
            $.ajax({
                url: '@Url.Action("Create", "m_Role")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal1").modal("show");
                    $(".modal-title").html("Add Role");
                }
            });
        }

        function DetailById(id) {
            $.ajax({
                url: '@Url.Action("Detail", "m_Role")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("View Role - @ViewBag.name");
                    $("#modal1").modal("show");
                }
            });
        }

        function GetById(id) {
            $.ajax({
                url: '@Url.Action("Edit", "m_Role")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Edit Role - ")
                    $("#modal1").modal("show");
                }
            });
        }

        function DeleteById(id) {
            $.ajax({
                url: '@Url.Action("Delete", "m_Role")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $("#body-delete").html(result);
                    $("#modal-delete").modal("show");
                }
            });
        }

        function rowPage(obj) {
            perPage = $(obj).attr('data-row');
            currPage = 1;
            GetList();
        }

        $("#btn-prev").click(function () {
            if (currPage > 1) {
                currPage--;
                $('#btn-next').removeClass('disabled');
            }
            GetList(currPage, perPage);
        });

        $("#btn-next").click(function () {
            if (currPage < maxPage) {
                currPage++;
                $('#btn-prev').removeClass('disabled');
            }
            GetList(currPage, perPage);
        });

        function DataSaved() {
        var saved = '<div class="alert alert-info alert-dismissible" role="alert"> <strong>Data Saved!</strong> New role has been add with code <strong>@ViewBag.Code !</strong> </div>';
        $("#alertbox").html(saved);
        $("#alertbox").slideUp(5000, function () {
            GetList();
        });
    }

    function DataUpdated() {
        var updated = '<div class="alert alert-info alert-dismissible" role="alert"> <strong>Data Updated!</strong> Data role has been updated <strong>!</strong> </div>';
        $("#alertbox").html(updated);
        $("#alertbox").slideUp(5000, function () {
            GetList();
        });
    }

    function DataDeleted() {
        var deleted = '<div class="alert alert-info alert-dismissible" role="alert"> <strong>Data Deleted!</strong> Data role has been deleted <strong>!</strong> </div>';
        $("#alertbox").html(deleted);
        $("#alertbox").slideUp(5000, function () {
            GetList();
        });
    }
    </script>
}

MarkomApp/Views/m_Role/_Create.cshtml
@model MA_ViewModel.m_RoleView

@using (Html.BeginForm("Create", "m_Role", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <p class="col-md-4 text-right">* Role Code</p>
            <div class="col-md-8">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", placeholder = "Auto Generated", style="max-width: 200px" } })
            </div>
        </div>

        <div class="form-group">
            <p class="col-md-4 text-right">* Role Name</p>
            <div class="col-md-8">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Role Name", style = "max-width: 200px" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="col-md-4 text-right">Description</p>
            <div class="col-md-8">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Description", style = "max-width: 200px" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 text-right">
                <div class="form-actions">
                    <input type="submit" value="Save" class="btn btn-primary" style="width: 80px" />
                    <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-warning" style="width: 80px" />
                </div>
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    var ent = result.entity;
                    $("#modal1").modal("hide");
                    DataSaved();
                }
            }
        })
        return false;
    })
</script>

MarkomApp/Views/m_Role/_Delete.cshtml
@model MA_ViewModel.m_RoleView

<div>
    <div class="form-horizontal">
        <div class="row">
            <div class="col-md-12 text-center" style="font-size: 15px">
                Delete Data ? <br /> <br />
            </div>
        </div>
    </div>

    @using (Html.BeginForm("Delete", "m_Role", FormMethod.Post, new { id = "form-delete", name = "form-delete" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id)
        <div class="col-md-offset-1">
            <div class="form-actions">
                <input type="submit" value="Delete" class="btn btn-primary" style="width: 80px" />
                <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-warning" style="width: 80px" />
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $("#form-delete").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#modal-delete").modal("hide");
                    DataDeleted();
                } else {
                    alert('Error: ' + result.message);
                }
            }
        })
        return false;
    })
</script>

MarkomApp/Views/m_Role/_Detail.cshtml
@model MA_ViewModel.m_RoleView
@Html.AntiForgeryToken()

@Html.HiddenFor(model => model.id)

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="form-group">
            <p class="col-md-4 text-right">* Role Code</p>
            <div class="col-md-8">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", style = "max-width: 200px" } })
            </div>
        </div>

        <div class="form-group">
            <p class="col-md-4 text-right">* Role Name</p>
            <div class="col-md-8">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", style = "max-width: 200px" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="col-md-4 text-right">Description</p>
            <div class="col-md-8">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", style = "max-width: 200px" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12 text-right">
            <input type="button" value="Close" data-dismiss="modal" class="btn btn-warning" style="width: 80px" />
        </div>
    </div>
</div>

MarkomApp/Views/m_Role/_Edit.cshtml
@model MA_ViewModel.m_RoleView

@using (Html.BeginForm("Edit", "m_Role", FormMethod.Post, new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        <div class="form-group">
            <p class="col-md-4 text-right">* Role Code</p>
            <div class="col-md-8">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", placeholder = "Auto Generated", style = "max-width: 200px" } })
            </div>
        </div>

        <div class="form-group">
            <p class="col-md-4 text-right">* Role Name</p>
            <div class="col-md-8">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Role Name", style = "max-width: 200px" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="col-md-4 text-right">Description</p>
            <div class="col-md-8">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Description", style = "max-width: 200px" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 text-right">
                <div class="form-actions">
                    <input type="submit" value="Update" class="btn btn-primary" style="width: 80px" />
                    <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-warning" style="width: 80px" />
                </div>
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#form-edit").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#modal1").modal("hide");
                    DataUpdated();
                }
            }
        })
        return false;
    })
</script>

MarkomApp/Views/m_Role/_List.cshtml
@model IEnumerable<MA_ViewModel.m_RoleView>

<style>
    .table {
        counter-reset: serial-number;
    }

        .table td:first-child:before {
            counter-increment: serial-number;
            content: counter(serial-number);
        }
</style>

<table class="table">
    <tr>
        <th>No</th>
        <th>Role Code</th>
        <th>Role Name</th>
        <th>Created Date</th>
        <th>Created By</th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.createdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.created_by)
            </td>
            <td>
                <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-default btn-detail" style="border:none" data-id="@item.id" title="View" onclick="DetailById(@item.id)">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                    <button type="button" class="btn btn-default btn-edit" style="border:none" data-id="@item.id" title="Edit" onclick="GetById(@item.id)">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </button>
                    <button type="button" class="btn btn-default btn-delete" style="border:none" data-id="@item.id" onclick="DeleteById(@item.id)" title="Delete">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </div>
            </td>
        </tr>
    }

</table>

<div class="col-md-offset-5 text-right">
    <button type="button" class="btn btn-primary" id="btn-prev">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
    </button>
    <span class="btn" style="border-color: grey; background: none; color: steelblue">@ViewBag.currPage</span>

    <button type="button" class="btn btn-primary" id="btn-next">
        <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
    </button>
</div>