MarkomApp/Controllers/t_EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MA_DataModel;
using MA_ViewModel;
using MA_Repository;

namespace MarkomApp.Controllers
{
    public class t_EventController : Controller
    {
        // GET: Event
        public ActionResult Index()
        {
            ViewBag.Code = t_EventRepo.GetNewCode();
            return View();
        }

        public ActionResult List(int page, string searchCode, int searchRequest, string createBy, int perPage)
        {
            Pagination pg = t_EventRepo.Paging(page, searchCode, searchRequest, createBy, perPage);
            ViewBag.currPage = page;
            ViewBag.PageCount = pg.Pages;
            return PartialView("_List", pg.ListOf);
        }

        public ActionResult SearchDate(DateTime createDate, DateTime requestDate)
        {
            return PartialView("_List", t_EventRepo.SearchDate(createDate, requestDate));
        }

        //Get
        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(t_EventView model)
        {
            ResponseResult result = t_EventRepo.Create(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    entity = result.Entity
                },
                JsonRequestBehavior.AllowGet);
        }

        //Get
        public ActionResult Edit(long id)
        {
            return PartialView("_Edit", t_EventRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Edit(t_EventView model)
        {
            ResponseResult result = t_EventRepo.Edit(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult Approval(long id)
        {
            ViewBag.EmployeeList = new SelectList(m_EmployeeRepo.All(), "id", "full_name");
            return PartialView("_Approval", t_EventRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Approval(t_EventView model)
        {
            ResponseResult result = t_EventRepo.Approval(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult Done(long id)
        {
            return PartialView("_Done", t_EventRepo.DoneById(id));
        }

        [HttpPost]
        public ActionResult Done(t_EventView model)
        {
            ResponseResult result = t_EventRepo.Done(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult Reject(long id)
        {
            return PartialView("_Reject", t_EventRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Reject(t_EventView model)
        {
            ResponseResult result = t_EventRepo.Reject(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);
        }
    }
}

MarkomApp/Views/t_Event/Index.cshtml
<br />
<div class="panel panel-primary">
    <div class="panel-heading">
        <p style="font-size:15px">List Event Request</p>
    </div>
    <div class="panel-body">
        <span class="label label-default" style="background-color: #EFEDED; font-size: 14px; color: grey"> @Html.ActionLink("Home", "Index", "Home") / @Html.ActionLink("List Employee", "Index", "t_Event")</span>
        <br />
        <div class="row">
            <div id="alertbox">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 text-right">
                <button type="button" class="btn btn-md btn-primary" onclick="AddEvent()">
                    Add
                </button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <input type="search" id="search-code" class="form-control" style="width:185px" placeholder="Transaction Code" />
            </div>
            <div class="col-md-2">
                <input type="search" id="search-request" class="form-control" style="width:185px" placeholder="Request By" />
            </div>
            <div class="col-md-2">
                <div class="input-group date">
                    <input type="text" id="requestdate" class="form-control" style="width:150px; border-right: none" placeholder="Request Date" onfocus="(this.type='date')" onblur="(this.type='text')">
                    <span class="input-group-addon btn" style="border-left:none; background: white">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="col-md-1">
                <div class="input-group">
                    <div class="dropdown">
                        <button type="button" id="status" style="width:90px" class="btn btn-md dropdown-toggle btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Status
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="#" value="1">Submitted</a></li>
                            <li><a href="#" value="2">In Progress</a></li>
                            <li><a href="#" value="3">Done</a></li>
                            <li><a href="#" value="0">Rejected</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="input-group date">
                    <input type="text" id="createdate" class="form-control" style="width:150px; border-right: none" placeholder="Created" onfocus="(this.type='date')" onblur="(this.type='text')">
                    <span class="input-group-addon btn" style="border-left:none; background: white">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                <input type="search" id="createby" class="form-control" style="width:185px" placeholder="Created By" />
            </div>
            <div class="col-md-1">
                <button type="button" id="btn-search" class="btn btn-md btn-warning">
                    Search
                </button>
            </div>
        </div>
        <div id="list-body">
            Loading...
        </div>
    </div>
</div>

<div id="modal1" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document" style="width: 750px">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <button type="button" style="color: white" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" style="color: white; font-size: 18px">Employee</h3>
            </div>
            <div class="modal-body">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="modal-reject" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document" style="width: 230px">
        <div class="modal-content">
            <div class="modal-body" id="body-reject">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts{
    <script type="text/javascript">
        var currPage = 1;
        var maxPage = 1;
        var perPage = 10;
        var searchCode = "";
        var searchRequest = 1;
        var requestDate;
        var status = 2;
        var createDate;
        var createBy = "";

        $(document).ready(function () {
            GetList()
        })

        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "t_Event")',
                type: 'get',
                data: { page: currPage, searchCode: searchCode, searchRequest: searchRequest, createBy: createBy, perPage: perPage },
                success: function (result) {
                    $("#list-body").html(result);
                    if (result = null) {
                        $("#list-body").html("Hasil tidak ditemukan");
                    };
                    if (currPage == 1) {
                        $('#btn-prev').addClass('disabled');
                    };
                }
            });
        }

        $("#btn-search").click(function () {
            searchCode = $("#search-code").val();
            searchRequest = $("#search-request").val();
            requestDate = $("#requestdate").val();
            status = $("#status").val();
            createDate = $("#createdate").val();
            createBy = $("#createby").val();
            if (createDate == "" && requestDate == "") {
                GetList();
            } else {
                $.ajax({
                    url: '@Url.Action("SearchDate","t_Event")',
                    type: 'get',
                    data: { createDate: createDate, requestDate: requestDate },
                    success: function (result) {
                        $("#list-body").html(result);
                    }
                });
            }

        })

        function AddEvent() {
            $.ajax({
                url: '@Url.Action("Create", "t_Event")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal1").modal("show");
                    $(".modal-title").html("Add Event Request");
                }
            });
        }

        function Approval(id) {
            $.ajax({
                url: '@Url.Action("Approval", "t_Event")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Approval Event Request - ");
                    $("#modal1").modal("show");
                }
            });
        }

        function EventDone(id) {
            $.ajax({
                url: '@Url.Action("Done", "t_Event")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Approval Event Request - ");
                    $("#modal1").modal("show");
                }
            });
        }

        function Reject(id) {
            $.ajax({
                url: '@Url.Action("Reject", "t_Event")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $("#body-reject").html(result);
                    $("#modal-reject").modal("show");
                }
            });
        }

        function GetById(id) {
            $.ajax({
                url: '@Url.Action("Edit", "t_Event")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Edit Event Request - ");
                    $("#modal1").modal("show");
                }
            });
        }

        function rowPage(obj) {
            perPage = $(obj).attr('data-row');
            currPage = 1;
            GetList();
        }

        $("#btn-prev").click(function () {
            if (currPage > 1) {
                currPage--;
                $('#btn-next').removeClass('disabled');
            }
            GetList(currPage, perPage);
        });

        $("#btn-next").click(function () {
            if (currPage < maxPage) {
                currPage++;
                $('#btn-prev').removeClass('disabled');
            }
            GetList(currPage, perPage);
        });

        function DataSaved() {
            var saved = '<div class="alert alert-info alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> <strong>Data Saved!</strong> Transaction event request has been add with code <strong>@ViewBag.Code !</strong> </div>';
            $("#alertbox").html(saved);
            $("#alertbox").slideUp(5000, function () {
                GetList();
            });
        }

        function DataUpdated() {
            var updated = '<div class="alert alert-info alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> <strong>Data Updated!</strong> Transaction event request has been updated <strong>!</strong> </div>';
            $("#alertbox").html(updated);
            $("#alertbox").slideUp(5000, function () {
                GetList();
            });
        }

        function DataApproved() {
            var approved = '<div class="alert alert-info alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> <strong>Data Approved !</strong> Transaction event request has been approved <strong>!</strong> </div>';
            $("#alertbox").html(approved);
            $("#alertbox").slideUp(5000, function () {
                GetList();
            });
        }

        function DataRejected() {
            var rejected = '<div class="alert alert-info alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> <strong>Data Rejected !</strong> Transaction event request has been rejected <strong>!</strong> </div>';
            $("#alertbox").html(rejected);
            $("#alertbox").slideUp(5000, function () {
                GetList();
            });
        }
    </script>
}

MarkomApp/Views/t_Event/_Approval.cshtml
@model MA_ViewModel.t_EventView

@using (Html.BeginForm("Approval", "t_Event", FormMethod.Post, new { id = "form-approval", name = "form-approval" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <p class="col-md-5 text-right">* Transaction Code</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Event Name</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.event_name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.event_name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Event Place</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.place, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.place, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Event Start Date</p>
                    <div class="col-md-7">
                        <div class="row">
                            <div class="input-group date">
                                @Html.EditorFor(model => model.start_date, new { htmlAttributes = new { @class = "form-control", style = "width:110px; border-right: none", @readonly = "readonly" } })
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.start_date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Event End Date</p>
                    <div class="col-md-7">
                        <div class="row">
                            <div class="input-group date">
                                @Html.EditorFor(model => model.end_date, new { htmlAttributes = new { @class = "form-control", style = "width:110px; border-right: none", @readonly = "readonly" } })
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.end_date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Budget (Rp.)</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.budget, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.budget, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Assign To</p>
                    <div class="col-md-7">
                        @Html.DropDownListFor(model => model.assign_to, (IEnumerable<SelectListItem>)ViewBag.EmployeeList, "- Select Employee -", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.assign_to, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <p class="col-md-5 text-right">* Request By</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.request_by, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.request_by, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Request Date</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.request_date, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.request_date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">Note</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.note, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", style = "height: 100px" } })
                        @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">Status</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.status_name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.request_date, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12 text-right">
                <div class="form-actions">
                    <input type="submit" value="Approved" class="btn btn-primary" style="width: 80px" />
                    <button type="button" class="btn btn-danger" style="width: 80px" onclick="Reject( new { id = @Html.HiddenFor(model => model.id) })">Rejected</button>
                    <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-warning" style="width: 80px" />
                </div>
            </div>
        </div>
    </div>
}



@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#form-approval").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#modal1").modal("hide");
                    DataApproved();
                }
            }
        })
        return false;
    })

    

</script>

MarkomApp/Views/t_Event/_Create.cshtml
@model MA_ViewModel.t_EventView

@using (Html.BeginForm("Create", "t_Event", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <p class="col-md-5 text-right">* Transaction Code</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", placeholder = "Auto Generated" } })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Event Name</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.event_name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Event Name" } })
                        @Html.ValidationMessageFor(model => model.event_name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Event Place</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.place, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Event Place" } })
                        @Html.ValidationMessageFor(model => model.place, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Event Start Date</p>
                    <div class="col-md-7">
                        <div class="row">
                            <div class="input-group date">
                                @Html.EditorFor(model => model.start_date, new { htmlAttributes = new { @class = "form-control", style = "width:110px; border-right: none", placeholder = "Select Date", onfocus = "(this.type='date')", onblur = "(this.type='text')" } })
                                <span class="input-group-addon btn" style="border-left:none; background: white">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.start_date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Event End Date</p>
                    <div class="col-md-7">
                        <div class="row">
                            <div class="input-group date">
                                @Html.EditorFor(model => model.end_date, new { htmlAttributes = new { @class = "form-control", style = "width:110px; border-right: none", placeholder = "Select Date", onfocus = "(this.type='date')", onblur = "(this.type='text')" } })
                                <span class="input-group-addon btn" style="border-left:none; background: white">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.end_date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Budget (Rp.)</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.budget, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Event Budget" } })
                        @Html.ValidationMessageFor(model => model.budget, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <p class="col-md-5 text-right">* Request By</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.request_by, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">* Request Date</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.request_date, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>

                <div class="form-group">
                    <p class="col-md-5 text-right">Note</p>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.note, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Note", style = "height: 100px" } })
                        @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12 text-right">
                <div class="form-actions">
                    <input type="submit" value="Save" class="btn btn-primary" style="width: 80px" />
                    <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-warning" style="width: 80px" />
                </div>
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    var ent = result.entity;
                    $("#modal1").modal("hide");
                    DataSaved()
                }
            }
        })
        return false;
    })
</script>

MarkomApp/Views/t_Event/_Reject.cshtml
@model MA_ViewModel.t_EventView

<div>
    <button type="button" class="close btn btn-danger text-right" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <div class="form-horizontal">
        <div class="row">
            <div class="col-md-12 text-center" style="font-size: 15px">
                Reject Reason
            </div>
        </div>
    </div>

    @using (Html.BeginForm("Reject", "t_Event", FormMethod.Post, new { id = "form-reject", name = "form-reject" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="row">
            <div class="form-group">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.reject_reason, new { htmlAttributes = new { @class = "form-control", placeholder = "Input Reject Reason", style = "height: 100px" } })
                    @Html.ValidationMessageFor(model => model.reject_reason, "", new { @class = "text-danger" })
                </div>
            </div>
        </div> <br />
        <div class="col-md-offset-1">
            <div class="form-actions">
                <input type="submit" value="Reject" class="btn btn-danger" style="width: 80px" />
                <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-warning" style="width: 80px" />
            </div>
        </div>
    }
</div>

@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $("#form-reject").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#modal-reject").modal("hide");
                    DataRejected();
                }
            }
        })
        return false;
    })
</script>